
ExternalProject_Add(builtins
    DOWNLOAD_COMMAND ""
    SOURCE_DIR ${LLVM_SRC_DIR}
    SOURCE_SUBDIR compiler-rt
    BUILD_IN_SOURCE 0
    UPDATE_COMMAND ""
    CMAKE_ARGS
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_TOOLCHAIN_FILE=${CMAKE_BINARY_DIR}/toolchain.cmake
        -DCMAKE_INSTALL_PREFIX=${TARGET_SYSROOT}/usr/local
        -DCMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY
        -DCMAKE_ASM_FLAGS=${TARGET_CONFIG}
        -DCMAKE_C_FLAGS=${TARGET_CONFIG}
        -DLLVM_CONFIG_PATH=${LLVM_BIN_DIR}/llvm-config
        -DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=ON
        -DCOMPILER_RT_BUILD_BUILTINS=ON
        -DCOMPILER_RT_BUILD_SANITIZERS=OFF
        -DCOMPILER_RT_BUILD_XRAY=OFF
        -DCOMPILER_RT_BUILD_LIBFUZZER=OFF
        -DCOMPILER_RT_BUILD_PROFILE=OFF
        -DCOMPILER_RT_DEFAULT_TARGET_ONLY=ON
)
add_dependencies(builtins clang)
if(BUILD_PLATFORM_SYSROOT)
    add_dependencies(builtins sysroot)
endif()
