SET(BUILTINS_CFLAGS "${TARGET_CONFIG} -I ${THIRD_PARTY_DIR}/musl/include -I ${THIRD_PARTY_DIR}/musl/arch/arm")

ExternalProject_Add(builtins
    DOWNLOAD_COMMAND ""
    SOURCE_DIR ${LLVM_SRC_DIR}
    SOURCE_SUBDIR compiler-rt
    BUILD_IN_SOURCE 0
    UPDATE_COMMAND ""
    CMAKE_ARGS
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_TOOLCHAIN_FILE=${CMAKE_BINARY_DIR}/toolchain.cmake
        -DCMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY
        -DCMAKE_INSTALL_PREFIX=${TOOLCHAIN_DIR}
        -DCMAKE_ASM_FLAGS=${TARGET_CONFIG}
        -DCMAKE_C_FLAGS=${BUILTINS_CFLAGS}
        -DLLVM_CONFIG_PATH=${LLVM_CONFIG_PATH}
        -DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=ON
        -DCOMPILER_RT_BUILD_BUILTINS=ON
        -DCOMPILER_RT_BUILD_SANITIZERS=OFF
        -DCOMPILER_RT_BUILD_XRAY=OFF
        -DCOMPILER_RT_BUILD_LIBFUZZER=OFF
        -DCOMPILER_RT_BUILD_PROFILE=OFF
        -DCOMPILER_RT_DEFAULT_TARGET_ONLY=ON
)
if(BUILD_PLATFORM_SYSROOT)
    add_dependencies(builtins sysroot)
endif()

SET(COMPILER_RT_C_FLAGS "${TARGET_CONFIG} -I${TARGET_SYSROOT}/usr/include/arm-linux-gnueabihf")
SET(COMPILER_RT_CXX_FLAGS "${TARGET_CONFIG}  -I${TARGET_SYSROOT}/usr/include/arm-linux-gnueabihf")
SET(COMPILER_RT_LINKER_FLAGS "-nostdlib -fuse-ld=lld")

ExternalProject_Add(compiler-rt
    DOWNLOAD_COMMAND ""
    SOURCE_DIR ${LLVM_SRC_DIR}
    SOURCE_SUBDIR compiler-rt
    BUILD_IN_SOURCE 0
    UPDATE_COMMAND ""
    CMAKE_ARGS
        -DCMAKE_TOOLCHAIN_FILE=${CMAKE_BINARY_DIR}/toolchain.cmake
        -DCMAKE_INSTALL_PREFIX=${TOOLCHAIN_DIR}
        -DCMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY
        -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
        -DCMAKE_ASM_FLAGS=${LIBCXX_C_FLAGS}
        -DCMAKE_C_FLAGS=${LIBCXX_C_FLAGS}
        -DCMAKE_CXX_FLAGS=${LIBCXX_CXX_FLAGS}
        -DCMAKE_SHARED_LINKER_FLAGS=${LIBCXX_LINKER_FLAGS}
#        -DLLVM_COMPILER_CHECKED=ON
        -DLLVM_PATH=${LLVM_SRC_DIR}/llvm
        -DLLVM_CONFIG_PATH=${LLVM_CONFIG_PATH}
        -DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=OFF
        -DCOMPILER_RT_STANDALONE_BUILD=OFF
        -DCOMPILER_RT_TARGET_TRIPLE=${TARGET_TRIPLE}
        -DCOMPILER_RT_SYSROOT=${TARGET_SYSROOT}
        -DCOMPILER_RT_BUILD_BUILTINS=OFF
        -DCOMPILER_RT_BUILD_SANITIZERS=ON
        -DCOMPILER_RT_BUILD_XRAY=ON
        -DCOMPILER_RT_BUILD_LIBFUZZER=ON
        -DCOMPILER_RT_BUILD_PROFILE=ON
        -DCOMPILER_RT_DEFAULT_TARGET_ONLY=OFF
)
add_dependencies(compiler-rt libcxx)
