
SET(LIBUNWIND_C_FLAGS ${TARGET_CONFIG})
SET(LIBUNWIND_CXX_FLAGS "-I{THIRD_PARTY_DIR}/llvm-project/libcxx/include ${TARGET_CONFIG}")
SET(LIBUNWIND_LINKER_FLAGS "-nostdlib -fuse-ld=lld")

ExternalProject_Add(libunwind
    DOWNLOAD_COMMAND ""
    SOURCE_DIR ${LLVM_SRC_DIR}
    SOURCE_SUBDIR libunwind
    BUILD_IN_SOURCE 0
    UPDATE_COMMAND ""
    CMAKE_ARGS
        -DCMAKE_TOOLCHAIN_FILE=${CMAKE_BINARY_DIR}/toolchain.cmake
        -DCMAKE_INSTALL_PREFIX=${TOOLCHAIN_DIR}
        -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
        -DCMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY
        -DLLVM_COMPILER_CHECKED=ON
        -DLLVM_CONFIG_PATH=${LLVM_CONFIG_PATH}
        -DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=OFF
        -DLIBUNWIND_SYSOOT=${TOOLCHAIN_DIR}
        -DLIBUNWIND_TARGET_TRIPLE=${TARGET_TRIPLE}
        -DLIBUNWIND_USE_COMPILER_RT=ON
        -DCMAKE_C_FLAGS=${LIBUNWIND_C_FLAGS}
        -DCMAKE_CXX_FLAGS=${LIBUNWIND_CXX_FLAGS}
        -DCMAKE_SHARED_LINKER_FLAGS=${LIBUNWIND_LINKER_FLAGS}
)

add_dependencies(libunwind musl)

